type state = s32
type blob = list<u8>
type input = string

/***************************/
/*     Handle functions    */
/***************************/

// Initializes an empty bloom filter
bloom-init-handle: func() -> state

// Adds a value to the bloom filter
bloom-update-handle: func(s: state, input: input) -> state

// Merges two bloom filters
bloom-merge-handle: func(left: state, right: state) -> state

// Serializes the bloom filter
bloom-serialize-handle: func(s: state) -> blob

// Deserializes the bloom filter
bloom-deserialize-handle: func(filter: blob) -> state

/***************************/
/*     Handle functions    */
/***************************/

// Checks if the value is MAYBE part of the set
bloom-maybe-exists: func(filter: blob, input: input) -> bool
